name: Release talosctl vendor tarball
on:
  push:
    branches:
    - main
    paths:
    - 'UPSTREAM_VERSION'

permissions:
  contents: write

jobs:
  package:
    name: Release talosctl vendor tarball
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - id: upstream-version
      run: |
        echo upstream-version=$(cat UPSTREAM_VERSION) >> $GITHUB_OUTPUT
        echo upstream-version-pep440=$(cat UPSTREAM_VERSION | cut -c2-) >> $GITHUB_OUTPUT
    - uses: robinraju/release-downloader@v1
      with:
        repository: siderolabs/talos
        tag: ${{ steps.upstream-version.outputs.upstream-version }}
        tarBall: true
        extract: true
    - run: mv siderolabs-talos-* talos-${{ steps.upstream-version.outputs.upstream-version-pep440 }}
    - uses: actions/setup-go@v5
    - working-directory: talos-${{ steps.upstream-version.outputs.upstream-version-pep440 }}
      run: GOWORK=off go mod vendor
    - run: tar --create --auto-compress --file talosctl-${{ steps.upstream-version.outputs.upstream-version-pep440 }}-deps.tar.gz talos-${{ steps.upstream-version.outputs.upstream-version-pep440 }}/vendor
    - uses: softprops/action-gh-release@v2
      with:
        draft: false
        prerelease: false
        name: talosctl-${{ steps.upstream-version.outputs.upstream-version-pep440 }}
        tag_name: ${{ steps.upstream-version.outputs.upstream-version }}
        body: This is a stub
        files: talosctl-${{ steps.upstream-version.outputs.upstream-version-pep440 }}-deps.tar.gz
